
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planifCours?createTableIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      #show-sql: true
      ddl-auto: update
      #ddl-auto: create
      #ddl-auto: validate
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
